apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history
  template:
    metadata:
      labels:
        app: history
    spec:
      imagePullSecrets:
      - name: azurecr-registry-secret
      containers: 
      - name: history
        image: tuplus.azurecr.io/history:1
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "80"
        - name: DBHOST
          value: mongodb://db:27017
        - name: DBNAME
          value: history
        - name: RABBIT
          value: amqp://test:test@rabbit:5672
---
apiVersion: v1
kind: Service
metadata:
  name: history
spec:
  selector:
    app: history
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
