apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata
  template:
    metadata:
      labels:
        app: metadata
    spec:
      imagePullSecrets:
      - name: azurecr-registry-secret
      containers: 
      - name: metadata
        image: tuplus.azurecr.io/metadata:1
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "80"
        - name: DBHOST
          value: mongodb://db:27017
        - name: DBNAME
          value: metadata
        - name: RABBIT
          value: amqp://test:test@rabbit:5672
---
apiVersion: v1
kind: Service
metadata:
  name: metadata
spec:
  selector:
    app: metadata
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
